In [56]:
import pandas as pd
import os
import matplotlib.pyplot as plt
from statistics import mean
from datetime import date


# convert Time notated in csv to amount of seconds.
def time_notation_to_sec(time_notation):
    # Check if incoming time_notation is non-empty
    # time_notation 3 variations; 00:07:30.300 or 07:30.300 07.30.300
    if isinstance(time_notation, str):
        time_notation = time_notation.replace(',', '.')
        split_string = time_notation.split(':')
        if len(split_string) > 2:   # variant like 00:07:30.300
            sec = (float(split_string[1]) * 60) +  float(split_string[2])
        elif len(split_string) == 2:   # variant like 07:30.300
            sec = (float(split_string[0]) * 60) +  float(split_string[1])
        else:       # variant like 7:30.300
            sec = (float(time_notation[0] * 60) + float(time_notation[2:]))            
    else:     # return empty string if empty entry
        return ''
    return sec

# Calculate watt from 500_m split in seconds.
def split_to_watt(split):
    return (split / 500) / pow(0.25, 3)

# TODO
def days_until_2k(training_date, two_k_date):
    days = 0
    return days

# Load .csv file and return raw dataframe
def load_dataset():
    cwd = os.getcwd()
    csv_path = cwd+"\okeanos.csv"
    return pd.read_csv(csv_path, delimiter=',', na_values=['', 'NA', 'N/A', 'NaN', 'nan'])

# return difference in days between 2 time notations of the form
# "dd-mm-yyyy'
def days_difference(date_training, date_2k):
    if (pd.isnull(date_2k)):
        return ''
        
    date_training_split = date_training.split('-')
    date_2k_split = date_2k.split('-')
    dtrain = date(int(date_training_split[2]), int(date_training_split[1]), int(date_training_split[0]))
    d2k = date(int(date_2k_split[2]), int(date_2k_split[1]), int(date_2k_split[0]))
    return (d2k - dtrain).days
    
if __name__ == "__main__":
    raw_df = load_dataset()
    # replace spaces with _ in columns
    #raw_df.columns = [col.replace(' ', '_') for col in raw_df.columns]
    raw_df = raw_df.rename(columns={"2k datum": "two_k_datum"})
    col_names = raw_df.columns.tolist()
    
    # Remove all completely empty rows or when theres only a single 2k date filled, 
    non_empty_df = raw_df.dropna(how='all', subset=(col_names[:-1]))

    #print(non_empty_df)

    # Add 500m split to seconds column 
    # Select all 500m_split entries and convert to seconds and insert new column into df
    col_500_split = non_empty_df.dropna(how='any', subset=('500_split')).loc[:,"500_split"]
    col_500_split_sec = col_500_split.apply(time_notation_to_sec)
    non_empty_df.insert(9, "500_split_sec", col_500_split_sec, True)
    
    # Add 2k time to seconds column 
    # Select all 2k_times entries and convert to seconds and insert new column into df
    col_two_k = non_empty_df.dropna(how='any', subset=('2k tijd')).loc[:,"2k tijd"]
    col_two_k_sec = col_two_k.apply(time_notation_to_sec)
    non_empty_df.insert(19, "2k_tijd_sec", col_two_k_sec, True)


    # Calculate amount days between training date and 2k date.
    #cols_datums = non_empty_df.dropna(how='any', subset=(['datum', '2k datum'])).loc[:,["500_split", "2k tijd"]]
    non_empty_df['days_until_2k'] = non_empty_df.apply(lambda x: days_difference(x.datum, x.two_k_datum), axis=1)
    
    #cols_datums_days = non_empty_df.apply(lambda x: f(x.datum, x.2k datum), axis=1)
    
    #non_empty_df.insert(19, "2k_tijd_sec", col_two_k_sec, True)
    #print(date_difference(two_k_split.loc[0],two_k_split.loc[10]))
    
    print(non_empty_df)

    non_empty_df.to_csv('okeanos_processed.csv')

           datum  ervaring geslacht gewichtsklasse ploeg naam zone  \
0     11-09-2018       1.0        M              Z   MGH  z47   AT
1     11-09-2018       1.0        M              Z   MGH  z47   AT
2     11-09-2018       1.0        M              Z   MGH  z47   AT
3     11-09-2018       1.0        M              Z   MGH  z47   AT
4     11-09-2018       1.0        M              Z   MGH  z47   AT
...          ...       ...      ...            ...   ...  ...  ...
6053   23-3-2023       1.0        V              L  mgld  ld5  NaN
6054   23-3-2023       1.0        V              L  mgld  ld1  NaN
6055   23-3-2023       1.0        V              L  mgld  ld2  NaN
6056   23-3-2023       1.0        V              L  mgld  ld4  NaN
6057   23-3-2023       1.0        V              Z   mjd  d19  NaN

     trainingype 500_split  500_split_sec  ... interval_afstand interval_tijd  \
0           5x5'    1:44.6          104.6  ...              NaN           300
1           5x5'    1:44.7          104.7  ...              NaN           300
2           5x5'    1:44.3          104.3  ...              NaN           300
3           5x5'    1:44.0          104.0  ...              NaN           300
4           5x5'    1:44.1          104.1  ...              NaN           300
...          ...       ...            ...  ...              ...           ...
6053        2000    1:57.4          117.4  ...           2000.0           NaN
6054        2000    1:51.3          111.3  ...           2000.0           NaN
6055        2000    1:48.6          108.6  ...           2000.0           NaN
6056        2000    1:55.5          115.5  ...           2000.0           NaN
6057        2000    1:54.7          114.7  ...           2000.0           NaN

      interval_nummer rust    machine    spm 2k tijd 2k_tijd_sec two_k_datum  \
0                   1  NaN  ergometer     26  6:19.9       379.9   8-12-2018
1                   2  NaN  ergometer     26  6:19.9       379.9   8-12-2018
2                   3  NaN  ergometer     26  6:19.9       379.9   8-12-2018
3                   4  NaN  ergometer     26  6:19.9       379.9   8-12-2018
4                   5  NaN  ergometer     26  6:19.9       379.9   8-12-2018
...               ...  ...        ...    ...     ...         ...         ...
6053                1  0.0  ergometer  vrij   7:49.8       469.8         NaN
6054                1  0.0  ergometer  vrij   7:25.4       445.4         NaN
6055                1  0.0  ergometer  vrij   7:14.6       434.6         NaN
6056                1  0.0  ergometer  vrij   7:42.2       462.2         NaN
6057                1  0.0  ergometer  vrij   7:38.9       458.9         NaN

      days_until_2k
0                88
1                88
2                88
3                88
4                88
...             ...
6053
6054
6055
6056
6057

[5707 rows x 22 columns]

C:\Users\Jan Hundling\AppData\Local\Temp\ipykernel_18576\708268873.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_empty_df['days_until_2k'] = non_empty_df.apply(lambda x: days_difference(x.datum, x.two_k_datum), axis=1)