In [63]:
import pandas as pd
import os
import matplotlib.pyplot as plt
from statistics import mean
from datetime import date


# convert Time notated in csv to amount of seconds.
def time_notation_to_sec(time_notation):
    # Check if incoming time_notation is non-empty
    # time_notation 3 variations; 00:07:30.300 or 07:30.300 07.30.300
    if isinstance(time_notation, str):
        time_notation = time_notation.replace(',', '.')
        split_string = time_notation.split(':')
        if len(split_string) > 2:   # variant like 00:07:30.300
            sec = (float(split_string[1]) * 60) +  float(split_string[2])
        elif len(split_string) == 2:   # variant like 07:30.300
            sec = (float(split_string[0]) * 60) +  float(split_string[1])
        else:       # variant like 7:30.300
            sec = (float(time_notation[0] * 60) + float(time_notation[2:]))            
    else:     # return empty string if empty entry
        return ''
    return sec

# Calculate watt from 500_m split in seconds.
def split_to_watt(split):
    return (split / 500) / pow(0.25, 3)

# TODO
def days_until_2k(training_date, two_k_date):
    days = 0
    return days

# Load .csv file and return raw dataframe
def load_dataset():
    cwd = os.getcwd()
    csv_path = cwd+"\okeanos.csv"
    return pd.read_csv(csv_path, delimiter=',', na_values=['', 'NA', 'N/A', 'NaN', 'nan'])

# return difference in days between 2 time notations of the form
# "dd-mm-yyyy'
def days_difference(date_training, date_2k):
    if (pd.isnull(date_2k)):
        return ''
        
    date_training_split = date_training.split('-')
    date_2k_split = date_2k.split('-')
    dtrain = date(int(date_training_split[2]), int(date_training_split[1]), int(date_training_split[0]))
    d2k = date(int(date_2k_split[2]), int(date_2k_split[1]), int(date_2k_split[0]))
    return (d2k - dtrain).days
    
    
if __name__ == "__main__":
    raw_df = load_dataset()
    # replace spaces with _ in columns
    #raw_df.columns = [col.replace(' ', '_') for col in raw_df.columns]
    raw_df = raw_df.rename(columns={"2k datum": "two_k_datum"})
    col_names = raw_df.columns.tolist()
    
    # Remove all completely empty rows or when theres only a single 2k date filled, 
    non_empty_df = raw_df.dropna(how='all', subset=(col_names[:-1]))


    # Add 500m split to seconds column 
    # Select all 500m_split entries and convert to seconds and insert new column into df
    col_500_split = non_empty_df.dropna(how='any', subset=('500_split')).loc[:,"500_split"]
    col_500_split_sec = col_500_split.apply(time_notation_to_sec)
    non_empty_df.insert(9, "500_split_sec", col_500_split_sec, True)
    
    # Add 2k time to seconds column 
    # Select all 2k_times entries and convert to seconds and insert new column into df
    col_two_k = non_empty_df.dropna(how='any', subset=('2k tijd')).loc[:,"2k tijd"]
    col_two_k_sec = col_two_k.apply(time_notation_to_sec)
    non_empty_df.insert(19, "2k_tijd_sec", col_two_k_sec, True)


    # Calculate amount days between training date and 2k date and add as days_until_2k column
    col_date_difference = non_empty_df.apply(lambda x: days_difference(x.datum, x.two_k_datum), axis=1)
    non_empty_df.insert(21, "days_until_2k", col_date_difference, True)

    #TODO 
    #Add column with mean interval 500_split

    #TODO
    # ADD column with wattage of 2k and 500_split

    #TODO
    # ADD column with integers instead of string variable?
    # geslacht, gewichtsklasse, trainingstype, zone  
    # dictionary_test = {'var1': 0, 'var2': 1, 'va........}
    # xxx = non_empty_df['......'] = non_empty_df.apply(lambda x: dictionary_test[variable_string], axis=1)
    # non_empty_df.insert(xx....)
    
    print(non_empty_df.head(50))
    non_empty_df.to_csv('okeanos_processed.csv')

         datum  ervaring geslacht gewichtsklasse ploeg naam zone trainingype  \
0   11-09-2018       1.0        M              Z   MGH  z47   AT        5x5'
1   11-09-2018       1.0        M              Z   MGH  z47   AT        5x5'
2   11-09-2018       1.0        M              Z   MGH  z47   AT        5x5'
3   11-09-2018       1.0        M              Z   MGH  z47   AT        5x5'
4   11-09-2018       1.0        M              Z   MGH  z47   AT        5x5'
5   11-09-2018       1.0        M              Z   MGH  z48   AT        5x5'
6   11-09-2018       1.0        M              Z   MGH  z48   AT        5x5'
7   11-09-2018       1.0        M              Z   MGH  z48   AT        5x5'
8   11-09-2018       1.0        M              Z   MGH  z48   AT        5x5'
9   11-09-2018       1.0        M              Z   MGH  z48   AT        5x5'
10  11-09-2018       1.0        M              Z   MGH  z49   AT        5x5'
11  11-09-2018       1.0        M              Z   MGH  z49   AT        5x5'
12  11-09-2018       1.0        M              Z   MGH  z49   AT        5x5'
13  11-09-2018       1.0        M              Z   MGH  z49   AT        5x5'
14  11-09-2018       1.0        M              Z   MGH  z49   AT        5x5'
15  11-09-2018       1.0        M              Z   MGH  z50   AT        5x5'
16  11-09-2018       1.0        M              Z   MGH  z50   AT        5x5'
17  11-09-2018       1.0        M              Z   MGH  z50   AT        5x5'
18  11-09-2018       1.0        M              Z   MGH  z50   AT        5x5'
19  11-09-2018       1.0        M              Z   MGH  z50   AT        5x5'
20  11-09-2018       1.0        M              Z   MGH  z51   AT        5x5'
21  11-09-2018       1.0        M              Z   MGH  z51   AT        5x5'
22  11-09-2018       1.0        M              Z   MGH  z51   AT        5x5'
23  11-09-2018       1.0        M              Z   MGH  z51   AT        5x5'
24  11-09-2018       1.0        M              Z   MGH  z51   AT        5x5'
25  11-09-2018       1.0        M              Z   MGH  z52   AT        5x5'
26  11-09-2018       1.0        M              Z   MGH  z52   AT        5x5'
27  11-09-2018       1.0        M              Z   MGH  z52   AT        5x5'
28  11-09-2018       1.0        M              Z   MGH  z52   AT        5x5'
29  11-09-2018       1.0        M              Z   MGH  z52   AT        5x5'
30  11-09-2018       1.0        M              Z   MGH  z53   AT        5x5'
31  11-09-2018       1.0        M              Z   MGH  z53   AT        5x5'
32  11-09-2018       1.0        M              Z   MGH  z53   AT        5x5'
33  11-09-2018       1.0        M              Z   MGH  z53   AT        5x5'
34  11-09-2018       1.0        M              Z   MGH  z53   AT        5x5'
35  11-09-2018       1.0        M              Z   MGH  z54   AT        5x5'
36  11-09-2018       1.0        M              Z   MGH  z54   AT        5x5'
37  11-09-2018       1.0        M              Z   MGH  z54   AT        5x5'
38  11-09-2018       1.0        M              Z   MGH  z54   AT        5x5'
39  11-09-2018       1.0        M              Z   MGH  z54   AT        5x5'
41  01-09-2018       1.0        M              Z   MGH  z47   ED       3x15'
42  01-09-2018       1.0        M              Z   MGH  z47   ED       3x15'
43  01-09-2018       1.0        M              Z   MGH  z47   ED       3x15'
44  01-09-2018       1.0        M              Z   MGH  z48   ED       3x15'
45  01-09-2018       1.0        M              Z   MGH  z48   ED       3x15'
46  01-09-2018       1.0        M              Z   MGH  z48   ED       3x15'
47  01-09-2018       1.0        M              Z   MGH  z49   ED       3x15'
48  01-09-2018       1.0        M              Z   MGH  z49   ED       3x15'
49  01-09-2018       1.0        M              Z   MGH  z49   ED       3x15'
50  01-09-2018       1.0        M              Z   MGH  z50   ED       3x15'

   500_split  500_split_sec  ... interval_afstand interval_tijd  \
0     1:44.6          104.6  ...              NaN           300
1     1:44.7          104.7  ...              NaN           300
2     1:44.3          104.3  ...              NaN           300
3     1:44.0          104.0  ...              NaN           300
4     1:44.1          104.1  ...              NaN           300
5        NaN            NaN  ...              NaN           300
6        NaN            NaN  ...              NaN           300
7        NaN            NaN  ...              NaN           300
8        NaN            NaN  ...              NaN           300
9        NaN            NaN  ...              NaN           300
10    1:45.6          105.6  ...              NaN           300
11    1:46.8          106.8  ...              NaN           300
12    1:48.2          108.2  ...              NaN           300
13    1:48.5          108.5  ...              NaN           300
14    1:47.8          107.8  ...              NaN           300
15    1:47.1          107.1  ...              NaN           300
16    1:45.5          105.5  ...              NaN           300
17    1:44.6          104.6  ...              NaN           300
18    1:43.8          103.8  ...              NaN           300
19    1:42.7          102.7  ...              NaN           300
20    1:45.9          105.9  ...              NaN           300
21    1:47.5          107.5  ...              NaN           300
22    1:49.3          109.3  ...              NaN           300
23    1:49.8          109.8  ...              NaN           300
24    1:49.6          109.6  ...              NaN           300
25    1:45.4          105.4  ...              NaN           300
26    1:45.1          105.1  ...              NaN           300
27    1:44.9          104.9  ...              NaN           300
28    1:44.5          104.5  ...              NaN           300
29    1:44.1          104.1  ...              NaN           300
30    1:44.3          104.3  ...              NaN           300
31    1:45.8          105.8  ...              NaN           300
32    2:32.5          152.5  ...              NaN           300
33    1:53.6          113.6  ...              NaN           300
34    1:53.7          113.7  ...              NaN           300
35    1:46.2          106.2  ...              NaN           300
36    1:47.8          107.8  ...              NaN           300
37    1:49.0          109.0  ...              NaN           300
38    1:49.9          109.9  ...              NaN           300
39    1:49.1          109.1  ...              NaN           300
41       NaN            NaN  ...              NaN           900
42       NaN            NaN  ...              NaN           900
43       NaN            NaN  ...              NaN           900
44       NaN            NaN  ...              NaN           900
45       NaN            NaN  ...              NaN           900
46       NaN            NaN  ...              NaN           900
47       NaN            NaN  ...              NaN           900
48       NaN            NaN  ...              NaN           900
49       NaN            NaN  ...              NaN           900
50       NaN            NaN  ...              NaN           900

    interval_nummer rust    machine  spm 2k tijd 2k_tijd_sec two_k_datum  \
0                 1  NaN  ergometer   26  6:19.9       379.9   8-12-2018
1                 2  NaN  ergometer   26  6:19.9       379.9   8-12-2018
2                 3  NaN  ergometer   26  6:19.9       379.9   8-12-2018
3                 4  NaN  ergometer   26  6:19.9       379.9   8-12-2018
4                 5  NaN  ergometer   26  6:19.9       379.9   8-12-2018
5                 1  NaN  ergometer   26  6:14.4       374.4   8-12-2018
6                 2  NaN  ergometer   26  6:14.4       374.4   8-12-2018
7                 3  NaN  ergometer   26  6:14.4       374.4   8-12-2018
8                 4  NaN  ergometer   26  6:14.4       374.4   8-12-2018
9                 5  NaN  ergometer   26  6:14.4       374.4   8-12-2018
10                1  NaN  ergometer   26     NaN         NaN   8-12-2018
11                2  NaN  ergometer   26     NaN         NaN   8-12-2018
12                3  NaN  ergometer   26     NaN         NaN   8-12-2018
13                4  NaN  ergometer   26     NaN         NaN   8-12-2018
14                5  NaN  ergometer   26     NaN         NaN   8-12-2018
15                1  NaN  ergometer   26  6:30.2       390.2   8-12-2018
16                2  NaN  ergometer   26  6:30.2       390.2   8-12-2018
17                3  NaN  ergometer   26  6:30.2       390.2   8-12-2018
18                4  NaN  ergometer   26  6:30.2       390.2   8-12-2018
19                5  NaN  ergometer   26  6:30.2       390.2   8-12-2018
20                1  NaN  ergometer   26     NaN         NaN   8-12-2018
21                2  NaN  ergometer   26     NaN         NaN   8-12-2018
22                3  NaN  ergometer   26     NaN         NaN   8-12-2018
23                4  NaN  ergometer   26     NaN         NaN   8-12-2018
24                5  NaN  ergometer   26     NaN         NaN   8-12-2018
25                1  NaN  ergometer   26  6:22.2       382.2   8-12-2018
26                2  NaN  ergometer   26  6:22.2       382.2   8-12-2018
27                3  NaN  ergometer   26  6:22.2       382.2   8-12-2018
28                4  NaN  ergometer   26  6:22.2       382.2   8-12-2018
29                5  NaN  ergometer   26  6:22.2       382.2   8-12-2018
30                1  NaN  ergometer   26     NaN         NaN   8-12-2018
31                2  NaN  ergometer   26     NaN         NaN   8-12-2018
32                3  NaN  ergometer   26     NaN         NaN   8-12-2018
33                4  NaN  ergometer   26     NaN         NaN   8-12-2018
34                5  NaN  ergometer   26     NaN         NaN   8-12-2018
35                1  NaN  ergometer   26  6:32.0       392.0   8-12-2018
36                2  NaN  ergometer   26  6:32.0       392.0   8-12-2018
37                3  NaN  ergometer   26  6:32.0       392.0   8-12-2018
38                4  NaN  ergometer   26  6:32.0       392.0   8-12-2018
39                5  NaN  ergometer   26  6:32.0       392.0   8-12-2018
41                1  NaN  ergometer   20  6:19.9       379.9   8-12-2018
42                2  NaN  ergometer   20  6:19.9       379.9   8-12-2018
43                3  NaN  ergometer   20  6:19.9       379.9   8-12-2018
44                1  NaN  ergometer   20  6:14.4       374.4   8-12-2018
45                2  NaN  ergometer   20  6:14.4       374.4   8-12-2018
46                3  NaN  ergometer   20  6:14.4       374.4   8-12-2018
47                1  NaN  ergometer   20     NaN         NaN   8-12-2018
48                2  NaN  ergometer   20     NaN         NaN   8-12-2018
49                3  NaN  ergometer   20     NaN         NaN   8-12-2018
50                1  NaN  ergometer   20  6:30.2       390.2   8-12-2018

    days_until_2k
0              88
1              88
2              88
3              88
4              88
5              88
6              88
7              88
8              88
9              88
10             88
11             88
12             88
13             88
14             88
15             88
16             88
17             88
18             88
19             88
20             88
21             88
22             88
23             88
24             88
25             88
26             88
27             88
28             88
29             88
30             88
31             88
32             88
33             88
34             88
35             88
36             88
37             88
38             88
39             88
41             98
42             98
43             98
44             98
45             98
46             98
47             98
48             98
49             98
50             98

[50 rows x 22 columns]